name: Commit Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Commitsar check
        uses: docker://aevea/commitsar
